# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user = User.create! :email => 'guy@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user = User.create! :email => 'keirl@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user = User.create! :email => 'kourtney@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user4 = User.create! :email => 'akila@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user11 = User.create! :email => 'guy11@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user12 = User.create! :email => 'guy12@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user13 = User.create! :email => 'guy13@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user14 = User.create! :email => 'guy14@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user15 = User.create! :email => 'guy15@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user16 = User.create! :email => 'guy16@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user17 = User.create! :email => 'guy17@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user18 = User.create! :email => 'guy18@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user19 = User.create! :email => 'guy19@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now

Profile.create(user_name: 'akila3',
               gender: 'Male',
               is_a_smoker: false,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               has_residence_already: true,
               street: '500 Riverside drive',
               city: 'New York',
               state: 'NY',
               postal_code: '10027',
               user_id: user4.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy11',
               gender: 'Male',
               is_a_smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user11.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user11.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy12',
               gender: 'Female',
               is_a_smoker: false,
               pet_friendly: true,
               cleanliness_level: 2,
               outgoingness_level: 2,
               quietness_level: 2,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user12.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user12.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy13',
               gender: 'Female',
               is_a_smoker: true,
               pet_friendly: false,
               cleanliness_level: 3,
               outgoingness_level: 3,
               quietness_level: 3,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user13.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user13.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy14',
               gender: 'Male',
               is_a_smoker: true,
               pet_friendly: false,
               cleanliness_level: 4,
               outgoingness_level: 4,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user14.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user14.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy15',
               gender: 'Female',
               is_a_smoker: true,
               pet_friendly: false,
               cleanliness_level: 5,
               outgoingness_level: 5,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user15.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user15.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy16',
               gender: 'Female',
               is_a_smoker: false,
               pet_friendly: true,
               cleanliness_level: 1,
               outgoingness_level: 3,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user16.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user16.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy17',
               gender: 'Male',
               is_a_smoker: true,
               pet_friendly: true,
               cleanliness_level: 5,
               outgoingness_level: 2,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user17.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user17.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy18',
               gender: 'Female',
               is_a_smoker: true,
               pet_friendly: true,
               cleanliness_level: 2,
               outgoingness_level: 1,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user18.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user18.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'guy19',
               gender: 'Male',
               is_a_smoker: false,
               pet_friendly: false,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 1,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user19.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 'Male',
               smoker: true,
               pet_friendly: false,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user19.id,
               latitude: nil,
               longitude: nil)

admin = Admin.create! :email => 'admin@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'